### ISSUE TITLE
Build totally broken (CashApplicationInfo.swift)

### ISSUE THREAD

**Issue by JediWed** [status-im/Keycard.swift#17]
It's not possible to build master nor 3.0.0
CashApplicationInfo.swift is totally broken.

1. Redeclaration of AppInfoTag
2. AppInfoTag incomplete
3. Usage of keyUID without having a reference
4. Usage of initializedCard without having a reference

**Comment by JediWed** [comment]
Last working commit: 096ace0535b9b822ce3bb7532341d54310469527

**Comment by bitgamma** [comment]
indeed, sorry about that. Fixed in latest commit and refined 3.0.0 tag
