### ISSUE TITLE
Unable to install through Cocoapods

### ISSUE THREAD

**Issue by luibo** [status-im/Keycard.swift#18]
Hi everyone, 
I want to integrate the Keycard Swift sdk in my project and I tried to install it through Cocoapods using the informations I found in the podspec file but Cocoapods keeps returning this error:

`[!] Unable to find a specification for 'Keycard'`

`You have either:`
`* out-of-date source repos which you can update with 'pod repo update' or with 'pod install --repo-update'.`
 `* mistyped the name or version.`
 `* not added the source repo that hosts the Podspec to your Podfile.`

I even tried to specify the source in the podfile but the error keeps showing. Is this not working because the cocoapods support is not ready yet?

**Comment by bitgamma** [comment]
Hello, yes you cannot use Cocoapods for that right now.

**Comment by togiter** [comment]
How can I do  integrate the Keycard Swift sdk in my project?  This is any demo?

**Comment by bitgamma** [comment]
there is an example here: https://github.com/gnosis/KeycardExample

**Comment by bitgamma** [comment]
Added Cocoapods support
