### ISSUE TITLE
Can't export chain code

### ISSUE THREAD

**Issue by luibo** [status-im/Keycard.swift#19]
I'll first explain what I'm trying to do. I need to perform account discovery as described here:

https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#account-discovery

in order to do that I first need to perform hardened derivation (ex. m/0'/0') to obtain a public extended key, then I should use this key with the chain code to derive all the paths I need for discovery (m/0/0-19) as described here:

https://bitcoin.stackexchange.com/questions/68740/generate-hd-addresses-using-publickey-bip44

After the hardened derivation is performed I can export the public key, but the chain code would always be null.

Apart from this, is it possible to export an xPub from the card?

**Comment by bitgamma** [comment]
we don't support exporting the chaining code/xPub keys. Only public keys can be exported. All key derivation must be performed on card.
