### ISSUE TITLE
Can't use the card because no pairing slots available

### ISSUE THREAD

**Issue by luibo** [status-im/Keycard.swift#20]
As I'm working actively with the card I use NFC sessions very often, the problem is that almost every operation with the card requires pairing but when an error occurs (for example "Tag connection lost") the card remains paired with that instance of the app (I guess). It happened during one of my tests that more than 5 NFC session failed consecutively due to "Tag connection lost", and now the card refuses to perform pairing as no pairing slots are available. Is there some way to repair this? Or the card is permanently locked?

**Comment by bitgamma** [comment]
You can reinstall the applet using the keycard-cli https://github.com/status-im/keycard-cli
