### ISSUE TITLE
Missing LoadForInstall and Load commands on GlobalPlatformCommandSet

### ISSUE THREAD

**Issue by rkreutz** [status-im/Keycard.swift#24]
Hey there,

I've been working on an iOS app to manage my Keycard and just happened to notice that the Android/Java SDK (and Go SDK) supports LoadForInstall and Load commands. I wanted to use these specially for upgrading/downgrading the Package version (I've noticed the Javacard repo has version 3.0.2 but my card is only at 3.0), I know I could use the CLI for that, but it would be nicer if I could use my phone for that.

So question is, any plans for adding these?

If there aren't any plans for it, do you have some kind of documentation/specification on how those commands should work (just like you have for Keycard commands on keycard.tech website), I'd be happy to help by opening a PR implementing this if I had that documentation.

Cheers

**Comment by bitgamma** [comment]
hello. We currently don't plan adding that function to th Swift SDK cause we don't use it in Status but we would happy to merge a PR with it. You can find the specifications at https://globalplatform.org/specs-library/card-specification-v2-3-1/. You can also refer to the code of the Java SDK for details

**Comment by rkreutz** [comment]
nice one thanks
