### ISSUE TITLE
Application Identifier

### ISSUE THREAD

**Issue by hiletmis** [status-im/Keycard.swift#29]
Hello,

I am trying to implement keycard ability to our iOS app but application identifier is not recognized.
We tried following identifiers but no-use;

	<key>com.apple.developer.nfc.readersession.iso7816.select-identifiers</key>
	<array>
		<string>A00000080400010101</string>
		<string>A00000080400010301</string>
		<string>A000000151000000</string>
	</array>

NFCReaderUsageDescription key is also set

	<key>NFCReaderUsageDescription</key>
	<string>Enable Keycard</string>

**Comment by bitgamma** [comment]
Hi. Make sure you also add entitlements as in https://github.com/status-im/status-mobile/blob/develop/ios/StatusImPR/StatusImPR.entitlements

in particular

```
<key>com.apple.developer.nfc.readersession.formats</key>
<array>
    <string>NDEF</string>
    <string>TAG</string>
</array>
```

**Comment by hiletmis** [comment]
Hey again. 

It's already set, forgot to mention about that. But still no response.
Cleaned the build also in case of cache

What am I missing?

Thanks!!

**Comment by bitgamma** [comment]
please give more details (bettera video) on what error you get and if possible a link to the repo to have a look at he code. Note that some iPhones have a very weak field and need the any eventual cover to be removed to work
